[package]
name = "rust_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
reth-db = { git = "https://github.com/BigBenlau/reth_ben", rev = "e524bdc9", package = "reth-db"}
reth-provider = { git = "https://github.com/BigBenlau/reth_ben", rev = "e524bdc9", package = "reth-provider"}
reth-primitives = { git = "https://github.com/BigBenlau/reth_ben", rev = "e524bdc9", package = "reth-primitives"}
reth-revm = { git = "https://github.com/BigBenlau/reth_ben", rev = "e524bdc9", package = "reth-revm"}
reth-node-ethereum = { git = "https://github.com/BigBenlau/reth_ben", rev = "e524bdc9", package = "reth-node-ethereum"}
reth-blockchain-tree = { git = "https://github.com/BigBenlau/reth_ben", rev = "e524bdc9", package = "reth-blockchain-tree"}
reth-beacon-consensus =  { git = "https://github.com/BigBenlau/reth_ben", rev = "e524bdc9", package = "reth-beacon-consensus"}
reth-interfaces = { git = "https://github.com/BigBenlau/reth_ben", rev = "e524bdc9", package = "reth-interfaces"}

revm-interpreter = { git = "https://github.com/BigBenlau/reth_ben", rev = "e524bdc9", package = "revm-interpreter"}

tracing = "0.1.0"
tracing-appender = "0.2"
chrono = "0.4.34"
csv = "1.3.0"
